DESIGN_NAME: topmodule
VERILOG_FILES: dir::src/*.v
CLOCK_PORT: clk
CLOCK_PERIOD: 15.0
PNR_SDC_FILE: dir::src/impl.sdc
SIGNOFF_SDC_FILE: dir::src/signoff.sdc
IO_PIN_ORDER_CFG: dir::pin_order.cfg
PDN_CORE_RING: true
PDN_ENABLE_RAILS: true
PDN_HORIZONTAL_LAYER: met5
PDN_VERTICAL_LAYER: met4
PDN_VOFFSET: 3
PDN_HOFFSET: 3
PDN_VWIDTH: 1.6
PDN_HWIDTH: 1.6
PDN_VPITCH: 30
PDN_HPITCH: 30
PDN_SKIPTRIM: true
PDN_CORE_RING_VWIDTH: 1.6
PDN_CORE_RING_HWIDTH: 1.6
PDN_CORE_RING_VOFFSET: 2
PDN_CORE_RING_HOFFSET: 2
PDN_CORE_RING_VSPACING: 1.7
PDN_CORE_RING_HSPACING: 1.7

pdk::sky130*:
  FP_CORE_UTIL: 55
  FP_SIZING: relative
  PL_TARGET_DENSITY: 0.60
  PL_ROUTABILITY_DRIVEN: true
  CLOCK_PERIOD: 15.0
  SYNTH_STRATEGY: "DELAY 0"
  SYNTH_SIZING: true
  MAX_FANOUT_CONSTRAINT: 16
  PL_RESIZER_TIMING_OPTIMIZATIONS: true
  GLB_RESIZER_TIMING_OPTIMIZATIONS: true
  scl::sky130_fd_sc_hd:
    CLOCK_PERIOD: 15.0
    MAX_FANOUT_CONSTRAINT: 16
  scl::sky130_fd_sc_hs:
    CLOCK_PERIOD: 15.0
    MAX_FANOUT_CONSTRAINT: 16
  scl::sky130_fd_sc_ls:
    CLOCK_PERIOD: 15.0
    MAX_FANOUT_CONSTRAINT: 16
pdk::gf180mcu*:
  CLOCK_PERIOD: 15.0
  FP_CORE_UTIL: 55
  PL_TARGET_DENSITY: 0.60
  PL_ROUTABILITY_DRIVEN: true
  SYNTH_STRATEGY: "DELAY 0"
  SYNTH_SIZING: true
  PL_RESIZER_TIMING_OPTIMIZATIONS: true
  GLB_RESIZER_TIMING_OPTIMIZATIONS: true
  MAX_FANOUT_CONSTRAINT: 16
